return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  dependencies = {
    'nvim-treesitter/nvim-treesitter-textobjects',
    'nvim-treesitter/nvim-treesitter-context',
    'HiPhish/rainbow-delimiters.nvim',
  },
  config = function()
    require('nvim-treesitter.configs').setup {
      ensure_installed = {
        'bash',
        'comment',
        'dockerfile',
        'html',
        'http',
        'latex',
        'lua',
        'make',
        'markdown',
        'markdown_inline',
        'python',
        'regex',
        'scala',
        'toml',
        'typst',
        'vimdoc',
        'yaml',
      },
      highlight = {
        enable = true,
      },
      indent = {
        enable = true,
      },
      incremental_selection = {
        enable = false,
      },
      rainbow = {
        enable = true,
      },
      textobjects = {
        swap = {
          enable = true,
          swap_next = {
            [')m'] = '@function.outer',
            [')c'] = '@comment.outer',
            [')a'] = '@parameter.inner',
            [')b'] = '@block.outer',
            [')C'] = '@class.outer',
          },
          swap_previous = {
            ['(m'] = '@function.outer',
            ['(c'] = '@comment.outer',
            ['(a'] = '@parameter.inner',
            ['(b'] = '@block.outer',
            ['(C'] = '@class.outer',
          },
        },
        move = {
          enable = true,
          set_jumps = true, -- set jumps in the jumplist
          goto_next_start = {
            -- [']]a'] = '@parameter.inner',
            -- [']]b'] = '@block.inner',
            -- [']]d'] = '@conditional.inner',
            -- [']]e'] = '@scopename.inner',
            -- [']]f'] = '@call.inner',
            -- [']]l'] = { query = '@class.inner', desc = 'next class start' },
            -- [']]m'] = '@function.inner',
            -- [']]o'] = '@loop.inner',
            -- [']]r'] = '@frame.inner',
            -- [']]t'] = '@attribute.inner',
            -- [']b'] = '@block.outer',
            -- [']d'] = '@conditional.outer',
            -- [']e'] = '@scopename.outer',
            -- [']r'] = '@frame.outer',
            -- [']t'] = '@attribute.outer',
            [']a'] = '@parameter.outer',
            [']c'] = '@comment.outer',
            [']f'] = '@call.outer',
            [']l'] = { query = '@class.outer', desc = 'next class start' },
            [']m'] = '@function.outer',
            [']o'] = '@loop.outer',
            [']s'] = '@statement.outer',
          },
          goto_next_end = {
            -- [']B'] = '@block.outer',
            -- [']C'] = '@comment.outer',
            -- [']D'] = '@conditional.outer',
            -- [']E'] = '@scopename.outer',
            -- [']R'] = '@frame.outer',
            -- [']T'] = '@attribute.outer',
            -- [']]A'] = '@parameter.inner',
            -- [']]B'] = '@block.inner',
            -- [']]D'] = '@conditional.inner',
            -- [']]E'] = '@scopename.inner',
            -- [']]F'] = '@call.inner',
            -- [']]L'] = '@class.inner',
            -- [']]M'] = '@function.inner',
            -- [']]O'] = '@loop.inner',
            -- [']]R'] = '@frame.inner',
            -- [']]T'] = '@attribute.inner',
            [']A'] = '@parameter.outer',
            [']F'] = '@call.outer',
            [']L'] = '@class.outer',
            [']M'] = '@function.outer',
            [']O'] = '@loop.outer',
            [']S'] = '@statement.outer',
          },
          goto_previous_start = {
            -- ['[[a'] = '@parameter.inner',
            -- ['[[b'] = '@block.inner',
            -- ['[[d'] = '@conditional.inner',
            -- ['[[e'] = '@scopename.inner',
            -- ['[[f'] = '@call.inner',
            -- ['[[l'] = '@class.inner',
            -- ['[[m'] = '@function.inner',
            -- ['[[o'] = '@loop.inner',
            -- ['[[r'] = '@frame.inner',
            -- ['[[t'] = '@attribute.inner',
            -- ['[b'] = '@block.outer',
            -- ['[d'] = '@conditional.outer',
            -- ['[e'] = '@scopename.outer',
            -- ['[r'] = '@frame.outer',
            -- ['[t'] = '@attribute.outer',
            ['[a'] = '@parameter.outer',
            ['[c'] = '@comment.outer',
            ['[f'] = '@call.outer',
            ['[l'] = '@class.outer',
            ['[m'] = '@function.outer',
            ['[o'] = '@loop.outer',
            ['[s'] = '@statement.outer',
          },
          goto_previous_end = {
            -- ['[B'] = '@block.outer',
            -- ['[D'] = '@conditional.outer',
            -- ['[E'] = '@scopename.outer',
            -- ['[R'] = '@frame.outer',
            -- ['[T'] = '@attribute.outer',
            -- ['[[A'] = '@parameter.inner',
            -- ['[[B'] = '@block.inner',
            -- ['[[D'] = '@conditional.inner',
            -- ['[[E'] = '@scopename.inner',
            -- ['[[F'] = '@call.inner',
            -- ['[[L'] = '@class.inner',
            -- ['[[M'] = '@function.inner',
            -- ['[[O'] = '@loop.inner',
            -- ['[[R'] = '@frame.inner',
            -- ['[[T'] = '@attribute.inner',
            ['[A'] = '@parameter.outer',
            ['[C'] = '@comment.outer',
            ['[F'] = '@call.outer',
            ['[L'] = '@class.outer',
            ['[M'] = '@function.outer',
            ['[O'] = '@loop.outer',
            ['[S'] = '@statement.outer',
          },
        },
      },
    }

    require('treesitter-context').setup {
      multiline_threshold = 1,
      trim_scope = 'inner'
    }
  end,
}
