# General settings
set -g default-terminal "tmux-256color"
set -g set-clipboard on
set -g mouse on

# Rebind Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Terminal — ghostty integration
set -ag terminal-features "ghostty:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Split panes
bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-yank'

set -g @smart-splits_no_wrap ''             # to disable wrapping. (any value disables wrapping)
set -g @smart-splits_move_left_key    'M-h' # key-mapping for navigation.
set -g @smart-splits_move_down_key    'M-j' #  --"--
set -g @smart-splits_move_up_key      'M-k' #  --"--
set -g @smart-splits_move_right_key   'M-l' #  --"--
set -g @smart-splits_resize_left_key  'C-h' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'C-j' #  --"--
set -g @smart-splits_resize_up_key    'C-k' #  --"--
set -g @smart-splits_resize_right_key 'C-l' #  --"--
set -g @smart-splits_resize_step_size '3'   # change the step-size for resizing.

# Theme
# mkdir -p ~/.config/tmux/plugins/catppuccin
# git clone -b v2.3.0 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_text ' #{s|/([^/])[^/]*|/\1|g:#{s|^/Users/[^/]+|~|:#{d:pane_current_path}}}/#{b:pane_current_path}'
set -g @catppuccin_window_current_text ' #{s|/([^/])[^/]*|/\1|g:#{s|^/Users/[^/]+|~|:#{d:pane_current_path}}}/#{b:pane_current_path}'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm-redux/tpm'
