# General settings
set -g default-terminal "tmux-256color"
set -g set-clipboard on
set -g mouse on

# Rebind Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Terminal — ghostty integration
set -ag terminal-features "ghostty:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# Split panes
bind '\' split-window -h -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"

# CMD+<number> -> select window <number> (sequences sent by ghostty)
set -s user-keys[0]  "\e[90;0~"
set -s user-keys[1]  "\e[90;1~"
set -s user-keys[2]  "\e[90;2~"
set -s user-keys[3]  "\e[90;3~"
set -s user-keys[4]  "\e[90;4~"
set -s user-keys[5]  "\e[90;5~"
set -s user-keys[6]  "\e[90;6~"
set -s user-keys[7]  "\e[90;7~"
set -s user-keys[8]  "\e[90;8~"
set -s user-keys[9]  "\e[90;9~"
bind -n User0 select-window -t :0
bind -n User1 select-window -t :1
bind -n User2 select-window -t :2
bind -n User3 select-window -t :3
bind -n User4 select-window -t :4
bind -n User5 select-window -t :5
bind -n User6 select-window -t :6
bind -n User7 select-window -t :7
bind -n User8 select-window -t :8
bind -n User9 select-window -t :9

# List of plugins
set -g @plugin 'mrjones2014/smart-splits.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-yank'

set -g @smart-splits_no_wrap ''             # to disable wrapping. (any value disables wrapping)
set -g @smart-splits_move_left_key    'M-h' # key-mapping for navigation.
set -g @smart-splits_move_down_key    'M-j' #  --"--
set -g @smart-splits_move_up_key      'M-k' #  --"--
set -g @smart-splits_move_right_key   'M-l' #  --"--
set -g @smart-splits_resize_left_key  'C-h' # key-mapping for resizing.
set -g @smart-splits_resize_down_key  'C-j' #  --"--
set -g @smart-splits_resize_up_key    'C-k' #  --"--
set -g @smart-splits_resize_right_key 'C-l' #  --"--
set -g @smart-splits_resize_step_size '3'   # change the step-size for resizing.

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm-redux/tpm'
